version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: "Table product"
        columns:
          - name: products_id
            description: "identification produit" 
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: "prix d'achat par produit"        
      - name: ship
        identifier: raw_gz_ship
        description: "Table ship"
        columns:
          - name: orders_id
            description: "identification de l'order"
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: "frais de livraison"
          - name: logcost
            description: "frais logistique" 
          - name: ship_cost
            description: "frais d'envoi"
      - name: sales
        identifier: raw_gz_sales
        description: "Table Sales"
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: date_date
            description: "date de vente"
          - name: orders_id
            description: "identification de l'order" 
          - name: products_id
            description: "identifiant produit"
          - name: revenue
            description: "chiffres d'affaire"
          - name: quantity
            description: "nb d'unité vendu"
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: adwords
        identifier: raw_gz_adwords
        tests:
              - unique:
                  column_name: campaign_key || '-' || date_date
        columns:
          - name: campgn_name
            tests:
              - not_null
          - name: campgain_key
            tests:
              - not_null
      - name: facebook
        identifier: raw_gz_facebook
        tests:
              - unique:
                  column_name: campaign_key || '-' || date_date
        columns:
          - name: campgn_name
            tests:
              - not_null
          - name: campgain_key
            tests:
              - not_null
      - name: criteo
        identifier: raw_gz_criteo
        tests:
              - unique:
                  column_name: campaign_key || '-' || date_date
        columns:
          - name: campgn_name
            tests:
              - not_null
          - name: campgain_key
            tests:
              - not_null
      - name: bing
        identifier: raw_gz_bing
        tests:
              - unique:
                  column_name: campaign_key || '-' || date_date
        columns:
          - name: campgn_name
            tests:
              - not_null
          - name: campgain_key
            tests:
              - not_null


